#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config normal_border_color '#707880'
bspc config active_border_color '#707880'
bspc config focused_border_color '#FFFFFF'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "r-menu" -o state=floating sticky=on window_type=dock border=off

# Configure screens
# XXX: YOU MAY NEED TO RECONFIGURE THIS ON YOUR OWN!
xrandr --output HDMI-1 --auto --output HDMI-0 --primary --right-of HDMI-1 --auto

# Auto Start
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
dunst &
polybar &
feh --bg-fill --no-xinerama ~/Pictures/Wallpapers/monochrome.jpg &

exec bspwm
